# Generated by Django 2.2.7 on 2019-11-18 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAAT', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.date(2019, 11, 18)),
            preserve_default=False,
        ),
    ]
