# Generated by Django 2.2.7 on 2019-11-20 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CAAT', '0003_profile_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='name',
            new_name='type',
        ),
        migrations.AddField(
            model_name='complaints',
            name='desc',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaints',
            name='image',
            field=models.ImageField(default='', upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaints',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
