# Generated by Django 3.0 on 2019-12-11 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAAT', '0004_auto_20191120_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='complaints',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('NOT_ATTENDED', 'Not Attended'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NOT_ATTENDED', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='type',
            field=models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('PLUMBER', 'Plumber'), ('CARPANTER', 'Carpanter'), ('AIR_CONDITIONER', 'Air_conditioner'), ('ROOM_CLEANING', 'Room_cleaning')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ELECTRICIAN', 'Electrician'), ('CARPENTER', 'Carpenter')], max_length=50),
        ),
    ]
