# Generated by Django 2.2.7 on 2019-12-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAAT', '0005_auto_20191211_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Floor',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Hostel',
            field=models.CharField(choices=[('L', 'L')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Room_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='image',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='type',
            field=models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('PLUMBER', 'Plumber'), ('CARPENTER', 'Carpenter'), ('AIR_CONDITIONER', 'Air_conditioner'), ('ROOM_CLEANING', 'Room_cleaning')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ELECTRICIAN', 'Electrician'), ('CARPENTER', 'Carpenter'), ('PLUMBER', 'plumber'), ('AIR_CONDITIONER', 'Air_conditioner'), ('ROOM_CLEANING', 'Room_cleaning')], max_length=50),
        ),
    ]
