# Generated by Django 2.2.7 on 2019-12-15 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAAT', '0006_auto_20191215_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
