# Generated by Django 2.2.7 on 2019-12-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAAT', '0007_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('Rating', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('VERY-GOOD', 'Very-good'), ('GOOD', 'GOOD'), ('AVERAGE', 'Average'), ('POOR', 'Poor')], max_length=11)),
            ],
        ),
    ]
