# Generated by Django 2.2.7 on 2019-11-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
